services:
  db:
    image: postgres:10-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: DemoPa$$$$
      POSTGRES_DB: demodb
    
    

  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports: 
      - "8081:8081"  
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      - db
    links:
      - "db:localhost"