services:
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports: 
      - "8081:8081"

  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports: 
      - 8080:8080
    depends_on:
      - db

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=DemoPa$$